apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureRequiredLabels
metadata:
  name: ns-mandatory-labels
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace", "Pod"]
    excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "default", "gatekeeper-system", "kured", "calico-system", "ingress-nginx", "tigera-operator"]
  parameters:
    labels: ["owner", "app", "role"]
