apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sazurerequiredlabels
metadata:
  name: ns-mandatory-labels
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "default", "gatekeeper-system", "kured", "calico-system", "ingress-nginx", "tigera-operator"]
  parameters:
    labels: 
     - key: owner
       allowedRegex: "^[a-zA-Z]+.cofcointernational.com$"
     - key: app
     - key: role
