---
- name: Test Windows Network Settings
  hosts: all
  tasks:
    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
    - debug: var=ipconfig

    - name: Windows Updates
      win_updates:
          category_names: 
          - CriticalUpdates
          - SecurityUpdates
          state: installed 
    - name: Reboot host if required
      win_reboot:
        when: update_result.reboot_required

      